const h1 = document.querySelector("h1");
h1.style.fontSize = "40px";
h1.style.color = "mediumblue";
h1.style.textTransform = "UpperCase";
h1.style.fontWeight = "500";
const article = document.querySelector("article");
article.style.width = "700px";
article.style.height = "600px";
article.style.backgroundColor = "deepskyblue";
article.style.display = "flex";
article.style.justifyContent = "center";
article.style.alignItems = "center";
const div = document.getElementById("firstDiv");
div.style.width = "650px";
div.style.height = "550px";
div.style.backgroundColor = "white";
div.style.borderRadius = "15px";
div.style.display = "flex";
div.style.alignItems = "center";
div.style.flexDirection = "column";
div.style.gap = "30px";
const inp = document.getElementById("textInp");
inp.style.width = "400px";
inp.style.height = "40px";
inp.style.border = "2px solid mediumblue";
const button = document.getElementById("addBtn");
button.style.width = "70px";
button.style.height = "40px";
button.style.borderRadius = "25px";
button.style.border = "none";
button.style.color = "white";
button.style.textTransform = "UpperCase";
button.style.fontWeight = "900";
button.addEventListener("click", () => {
  const inpValues = inp.value.trim("");
  const pTag = document.createElement("p");
  const btn = document.createElement("button");
  btn.style.width = "60px";
  btn.style.height = "30px";
  btn.style.border = "none";
  btn.style.color = "white";
  btn.style.borderRadius = "50px";
  btn.textContent = "delete";
  btn.style.textTransform = "UpperCase";
  btn.style.fontSize = "10px";
  btn.style.fontWeight = "800";
  btn.style.backgroundColor = "rgb(255, 20, 110)";
  pTag.style.width = "500px";
  pTag.style.height = " 50px";
  pTag.style.color = "white";
  pTag.style.fontWeight = "700";
  pTag.style.display = "flex";
  pTag.style.justifyContent = "space-between";
  pTag.style.alignItems = "center";
  pTag.style.backgroundColor = "deepskyblue";
  div.appendChild(pTag);
  pTag.appendChild(btn);
  pTag.textContent = inpValues;
  inp.value = "";
  document.body.appendChild(pTag.append(btn));
  btn.addEventListener("click", () => {
    pTag.remove();
  });
});
